# Singular Value Decomposition
## Assignment 2: Question 2

### Initializing the libraries

In [36]:
import numpy as np
from sklearn.datasets import load_boston as boston


### Generating a random matrix

In [5]:
A = np.random.randint(10,size = (5,5))
A

array([[7, 6, 5, 6, 5],
       [0, 3, 9, 7, 2],
       [0, 8, 7, 5, 0],
       [0, 5, 8, 4, 1],
       [8, 0, 3, 3, 0]])

In [8]:
np.linalg.matrix_rank(A)

5

### Calculating U

In [10]:
A_t = np.transpose(A)
A_t

array([[7, 0, 0, 0, 8],
       [6, 3, 8, 5, 0],
       [5, 9, 7, 8, 3],
       [6, 7, 5, 4, 3],
       [5, 2, 0, 1, 0]])

In [12]:
AA_t = A.dot(A_t)
AA_t

array([[171, 115, 113,  99,  89],
       [115, 143, 122, 117,  48],
       [113, 122, 138, 116,  36],
       [ 99, 117, 116, 106,  36],
       [ 89,  48,  36,  36,  82]])

In [24]:
w1,v1 = np.linalg.eig(AA_t)

In [34]:
U = v1
w1[::-1].sort() #sorting the eigenvalues in descending order
sig = np.diag(w1)
sig

array([[508.22532092,   0.        ,   0.        ,   0.        ,
          0.        ],
       [  0.        ,  94.8793007 ,   0.        ,   0.        ,
          0.        ],
       [  0.        ,   0.        ,  23.02209465,   0.        ,
          0.        ],
       [  0.        ,   0.        ,   0.        ,  12.16591682,
          0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          1.70736691]])

### Calculating V

In [35]:
A_tA = A_t.dot(A)
w2,v2 = np.linalg.eig(A_tA)
V = v2
w2[::-1].sort() #sorting the eigenvalues in descending order
sig2 = np.diag(w2)
sig2


array([[508.22532092,   0.        ,   0.        ,   0.        ,
          0.        ],
       [  0.        ,  94.8793007 ,   0.        ,   0.        ,
          0.        ],
       [  0.        ,   0.        ,  23.02209465,   0.        ,
          0.        ],
       [  0.        ,   0.        ,   0.        ,  12.16591682,
          0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          1.70736691]])

We observe that the sigma we got from the AAt calculation (for U) is the same as the one from AtA calculation (for V)

### Dimensionaltiy Reduction using SVD

We see that the 